---
name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        user: docker/login-action@v1
        with:
          username: ${{secret.DOCKER_HUB}}
          password: ${{secret.DOCKER_TOKEN}}
      - name: checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: lint
        run: docker-compose run --rm app sh -c "flake8"